<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrceoye\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrceoye/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCrceoye.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCrceoye\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCrceoye\appProdProjectContainer([
    'container.build_hash' => 'Crceoye',
    'container.build_id' => 'e7924f07',
    'container.build_time' => 1559649264,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrceoye');
